### ISSUE TITLE
I have obtained the key to success

### ISSUE THREAD

**Issue by carnau** [michaelbiberich/the-key-to-success#5]
Name: Carlos Arnau Ros
Date: 2018-08-30
Verification: abb3d6da92fcce9ddf378b693f37a119861e68b5

**Comment by michaelbiberich** [comment]
**Thank you** for trying to obtain the key to success!

Unfortunately I _cannot_ verify your claim.

Something seems to be _off_ regarding the **Verification** hash.
Expected hash: `***********************************e68b5`

Can you _please_ check again if this is the _correct_ **Verification** hash?
I'll be happy to help/answer any questions, _as long as it doesn't spoil anything_.

**Sorry** for the inconvenience.

**Comment by carnau** [comment]
I updated the Verification code :-)

**Comment by michaelbiberich** [comment]
Thank you and Congratulations!

You have been added to the [Official List of Winners](https://github.com/michaelbiberich/the-key-to-success/blob/master/winners.txt).
